apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infrastructure
  path: "./apps"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
