apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgAKU7u/84Ec0vRXBsYZmSyTHLaHnBx2cU5mA/jHbY+rhGt8MzM3GwKm02umr7QuMKIF3laWQHJ94FJreP9Jtjc+0ksolA3dXJFVHokGUsDTNvj9bPoRejDuxauszaee5I2iFw52R9Bv60sffvCo1N3IevtZiZI4ukY4u6/aIZHxy7ZletWJN25a3ZqQKb1Q/aJjdBTMST3vTIBNlbGDYZgBh9MBp08DLIrAqLk7Vxy+2Rky5zoBCSQ8GYaoFrWteAT25sWCop0OEkuScFkd3TALeYy44dpUciVhwZdkjzM0QAAQ9YbFNzgPY+K/kseRcTD5utvtsDG9f4MUSriWvQpNnLKZxHm0E7RNoHNfj92mK5cngzOKSQO353SVqkowvus0dA58AurnFA+w5kA9rn/CBeH+VcOsBw1/X+u+QdTDaeWPgCWORKbZKuAdEjgmoy0i1KVzT6S0cEAObOTVr+OeBJaZiE6ytohSIphSR2Yuy4h7i6FdLvD8Cgdwlea8HN7hNaF8JQff9skr+09zIbteRDtUleduTPdCAeUk8e01QSDY/k3+wGyR0f3Tlp9MRisVsawxQMuNQGoAwG+oVqmNAYeDRxg4Xsju4kihzZ2WTYe/Vcgdqr95K0kotlHW68x+VUdrAZNpjLciMZo37w5L5NSoS7L1LFQSbRiiCRcCkCFgtaOMvIoEUWdcMbhk+6lKTjkTaiNbgMg=
    DB_USERNAME: AgAXx5867HyQKqOOZY84JWbPwm/HLaIWPejD/UDHVGJ9U326Np+hyPyfhLIzCej/Rb7amIaHC0IMGefI7ohZAfKCyKT51lHamSA97IRNCg8Qow6+I2PXNc2zJSg+BCd0g8CGkvIpNHREnb5+wT8UzE7wzyke3urgkv42ZTJMin9bC4zFi7A3rJ793I1vgLSKRvKOfs1r4hRFhOkGmfxhFuITMFzWKk2yvUO5/qvpVfyjjbnt0XFE2anu8FPpck56H12XV2HuLtrOhCmm9XFp1JW/9pSgt2CqFUKsOsn9lMOAXcMzM9qI+F54qo4FcgZgalxGNY6+BkSoIkh5Z4mzZNsz8DBdWTiLiw46yTHE03ymj1GoQZ6pXV+OS5Vso9PlKQJDumT5Y/d22rv/EfSL8ma0+0lxxktVmZLH12QPiJneFPli9FeT8TIYKyCgEUcLqHCHc7J5j92fxEyMvfGbemNMSOnP9EIb5u1bUaq4QEo4nSHqoE38aFXXbaPwpyq+VdaNWrjZRoYkb9rz6wwMB8r7jbo5RjDm2zjQ/Us+3HABoUaclFz9uTNYXO9sg/IAXv1MIP7t9Wljh7SEYaTaSVAVV4mKgLI6x1MVTtAXfZHItUe4TKKqRKMfKbAt4wjenkM/cJQfCS4lfn2dveHSkGERaU9z93CFr4C5qbb95CbjXCgzpA+0r4FXQIvBrZ+TnqsZfXP/0shAdA==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
---
