apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: apache
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: apache
      version: 10.2.4
      sourceRef:
        kind: HelmRepository
        name: apache
        namespace: flux-system
      interval: 1m
